# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "master" ]
    tags: [ "v*" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: write


jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0  # Fetch all history for git describe

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.24.3'

    - name: Build
      run: make

    - name: Build Docker Image
      run: |
        docker build -t ghcr.io/fatemehkarimi/chronos_bot:${{ github.run_number }} .
        docker build -t ghcr.io/fatemehkarimi/chronos_bot:latest .

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GHCR_PAT }}

    - name: Push Docker Image
      run: |
        docker push ghcr.io/fatemehkarimi/chronos_bot:${{ github.run_number }}
        docker push ghcr.io/fatemehkarimi/chronos_bot:latest

    - name: Test
      run: go test -v ./...

    - name: Create and push git tag
      if: github.ref == 'refs/heads/master' && github.event_name == 'push'
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
        
        TAG="v$(date +%Y.%m.%d)-${{ github.run_number }}"
        git tag $TAG
        
        git push origin $TAG
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
